cache does not help no

diff --git a/.github/actions/build-docker-image/action.yml b/.github/actions/build-docker-image/action.yml
--- a/.github/actions/build-docker-image/action.yml
+++ b/.github/actions/build-docker-image/action.yml
@@ -10,8 +10,6 @@ inputs:
   TAG:
     description: 'DigitalOcean Registry Tag'
     required: true
-  DIGITALOCEAN_ACCESS_TOKEN:
-    description: "DigitalOcean Access token"
  
 runs:
   using: composite
@@ -19,21 +17,25 @@ runs:
     - name: Checkout repository
       uses: actions/checkout@v3
 
-    - name: Set up Docker Buildx
-      uses: docker/setup-buildx-action@v3
+    - name: Build container image
+      run: |
+        SHORT_SHA=$(echo $GITHUB_SHA | head -c7)
+        docker build -t ${{ inputs.REGISTRY_URL }}/${{ inputs.REPOSITORY }}:$SHORT_SHA .
+      shell: bash
 
-    - name: Log in to DigitalOcean Container Registry
-      uses: docker/login-action@v3
-      with:
-        registry: ${{ inputs.REGISTRY_URL }}
-        username: ${{ inputs.DIGITALOCEAN_ACCESS_TOKEN }}
-        password: ${{ inputs.DIGITALOCEAN_ACCESS_TOKEN }}
+    - name: Push image to DigitalOcean Container Registry
+      run: |
+        TIMESTAMP=$(date +%Y%m%d%H%M%S)
+        SHORT_SHA=$(echo $GITHUB_SHA | head -c7)
 
-    - name: Build and push Docker image
-      uses: docker/build-push-action@v5
-      with:
-        context: .
-        push: true
-        tags: ${{ inputs.REGISTRY_URL }}/${{ inputs.REPOSITORY }}:${{ inputs.TAG }}
-        cache-from: type=gha
-        cache-to: type=gha,mode=max
+        # Debugging - Check if image exists
+        docker images | grep $SHORT_SHA || echo "Image not found!"
+
+        docker tag ${{ inputs.REGISTRY_URL }}/${{ inputs.REPOSITORY }}:$SHORT_SHA ${{ inputs.REGISTRY_URL }}/${{ inputs.REPOSITORY }}:${{ inputs.TAG }}
+        docker tag ${{ inputs.REGISTRY_URL }}/${{ inputs.REPOSITORY }}:$SHORT_SHA ${{ inputs.REGISTRY_URL }}/${{ inputs.REPOSITORY }}:$TIMESTAMP
+
+        docker push ${{ inputs.REGISTRY_URL }}/${{ inputs.REPOSITORY }}:${{ inputs.TAG }}
+        docker push ${{ inputs.REGISTRY_URL }}/${{ inputs.REPOSITORY }}:$TIMESTAMP
+      shell: bash
+    
+    
